name: CI Pipeline

on:

  push:

    branches:

      - main

  pull_request:

    branches:

      - main

  workflow_dispatch:


jobs:

  lab3:
  
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 bandit  # Установка дополнительных пакетов

      - name: Run tests with coverage
        run: pytest --cov=script test_script.py  # Запуск тестов с проверкой покрытия

      - name: Run linting
        run: flake8 script.py test_script.py --exclude=env

      - name: Run security check
        run: bandit -r . -x ./env/Lib/site-packages  # Проверка безопасности с bandit

       # Этап для отправки уведомления в Telegram
      - name: Send Telegram Notification about Pipeline Status
        if: always()  # Выполняется всегда, независимо от статуса
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Проверка статуса пайплайна
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="успешно"
            MESSAGE="CI/CD Pipeline завершен успешно для ветки ${{ github.ref_name }}."
          else
            STATUS="с ошибкой"
            MESSAGE="CI/CD Pipeline завершен с ошибкой для ветки ${{ github.ref_name }}."
          fi
          
          # Отправляем сообщение через Telegram API
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="$MESSAGE"